module.exports = {
  darkMode: 'class',
  content: [
  "./src/app/**/*.{html,ts}",
  "./src/index.html"
],
   darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "secondary-fixed-dim": "#a8d5b2",
                        "inverse-primary": "#88d982",
                        "surface-dim": "#dadada",
                        "surface-container-high": "#c8e6c9",
                        "secondary-container": "#c8e6c9",
                        "on-primary-fixed": "#002204",
                        "tertiary-container": "#2e7d32",
                        "on-secondary-container": "#1b5e20",
                        "surface-tint": "#1b6d24",
                        "primary-fixed-dim": "#88d982",
                        "on-secondary-fixed": "#1b5e20",
                        "tertiary": "#388e3c",
                        "on-tertiary-container": "#e8f5e9",
                        "tertiary-fixed": "#a5d6a7",
                        "on-tertiary": "#ffffff",
                        "surface-container-highest": "#e2e2e2",
                        "surface-container": "#eeeeee",
                        "inverse-surface": "#2f3131",
                        "secondary-fixed": "#c8e6c9",
                        "outline": "#707a6c",
                        "on-tertiary-fixed-variant": "#1b5e20",
                        "inverse-on-surface": "#f1f1f1",
                        "on-error-container": "#93000a",
                        "on-primary-container": "#cbffc2",
                        "on-background": "#1a1c1c",
                        "surface-variant": "#e2e2e2",
                        "tertiary-fixed-dim": "#81c784",
                        "primary-container": "#2e7d32",
                        "surface-bright": "#f9f9f9",
                        "primary-fixed": "#a3f69c",
                        "on-primary": "#ffffff",
                        "surface-container-lowest": "#ffffff",
                        "primary": "#0d631b",
                        "outline-variant": "#bfcaba",
                        "on-secondary-fixed-variant": "#603f33",
                        "on-primary-fixed-variant": "#005312",
                        "error-container": "#ffdad6",
                        "on-tertiary-fixed": "#331200",
                        "on-secondary": "#ffffff",
                        "error": "#ba1a1a",
                        "background": "#f9f9f9",
                        "surface-container-low": "#f3f3f3",
                        "on-error": "#ffffff",
                        "surface": "#f9f9f9",
                        "on-surface": "#1a1c1c",
                        "secondary": "#7a5649",
                        "on-surface-variant": "#40493d",
                        "background-light": "#f8f8f5",
                        "background-dark": "#23220f",
                    },
                    "borderRadius": {
                        "DEFAULT": "1rem",
                        "md": "1.5rem",
                        "lg": "2rem",
                        "xl": "3rem",
                        "full": "9999px"
                    },
                    "fontFamily": {
                        "headline": ["Manrope"],
                        "body": ["Inter"],
                        "label": ["Inter"],
                        "display": ["Spline Sans", "sans-serif"]
                    }
                }
            },
  plugins: [require('@tailwindcss/container-queries')],
}
